<script src="/vendor/@popperjs/core/dist/umd/popper.min.js"></script>
<script src="/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/vendor/onscreen/dist/on-screen.umd.min.js"></script>
<script src="/vendor/nouislider/dist/nouislider.min.js"></script>
<script src="/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
<script src="/vendor/chartist/dist/chartist.min.js"></script>
<script src="/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
<script src="/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>
<script src="/vendor/sweetalert2/dist/sweetalert2.all.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js"></script>
<script src="/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>
<script src="/vendor/notyf/notyf.min.js"></script>
<script src="/vendor/simplebar/dist/simplebar.min.js"></script>
<script async defer src="https://buttons.github.io/buttons.js"></script>
<script src="/assets/js/volt.js"></script>
